
#Application Configuration
server:
  port: 8093
  error:
    include-message: always

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
  sql:
    init:
      platform: h2
        
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: always      
  config:
    import: "optional:configserver:"

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false